### PR TITLE
- allow the interpolation of individual series' via the <px-vis-data-converter>

### PR DESCRIPTION
**Pull request by davidsteinberger**
* ## A description of the changes proposed in the pull request:

This PR allows the _interpolation by series_ feature (added in v1.1.0) to be used in conjunction with the `<px-vis-data-converter>`.

* ## A reference to a related issue (if applicable):

https://github.com/PredixDev/px-vis-timeseries/issues/40

* ## @mentions of the person or team responsible for reviewing proposed changes:

@nonmetalhail 

* ## working tests:

_test/px-vis-data-converter-tests.js_

### CODE REVIEW

**Comment by nonmetalhail** [comment]
Thanks for the PR. You're right that the JSON parse and stringify is a problem as it prevents functions and special values such as Infinity from being passed in. It was in there to prevent seriesConfig and completeSeriesConfig from being linked and live as their own separate objects. I'll have to look into if this is a problem and if so, an alternate approach to clone the object before I can merge.

**Comment by davidsteinberger** [comment]
Thanks. If you want me to clone the object just let me know and I'll add it.

**Comment by nonmetalhail** [comment]
So I confirmed that the two are linked as a result of this. Although I dont know if it actually matters, I think we should be cautious and clone the object. It's annoying since it is a deeply nested object. If you have the time to do this, that would be great. Maybe make a method to clone so we can reuse it in the future if needed. 

If you dont get around to it, I will some time next week.

**Comment by davidsteinberger** [comment]
Added the clone method and all tests passed. But after a recent merge of _master_ the test-suite fails for me with `Cannot read property 'select' of undefined <unknown> at px-vis-line-svg-tests.js:1350`. Is that an issue on master?

**Comment by nonmetalhail** [comment]
Hmm... I don't think so. I'll have to take a look

**Comment by davidsteinberger** [comment]
It's interesting. When I run `wct` on master it fails almost every time on Chrome 56. When I run that particular test in Chrome 56 manually, it usually passes. When I pump up the timeouts from 100 to 300ms they pass via `wct`.

**Comment by nonmetalhail** [comment]
Futzing around with it yesterday, I think it is fine. Not sure why the travis tests were failing. Rerunning them caused them to pass. But it appears that only the Chrome and Firefox tests were running on Travis, so today I'm going to just do a quick check on IE & Edge and try to find Chrome 56 and give that a shot. But I think we're all good.

I'm probably going to wait until the end of the week to actually merge; a big client is shipping this week and I'd rather play it safe and add this after. 

Thanks for the PR!

**Comment by nonmetalhail** [comment]
Merged! Available in v1.1.8. Thanks!

**Pull request merged**
